### ISSUE TITLE
Mopidy Skill fails and mycroft starts playin news instead

### ISSUE THREAD

**Issue by klundry** [forslund/mopidy_skill#31]
It seems like mopidy skill is at least partially functioning because it says it finds a match for what I asked but then starts playing a news feed instead.

Here is the skills log:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.mycroft.ai', port=443): Max retries exceeded with url: /v1/device/1abe5239-13c0-4ac9-9617-a3ff56fe7711/skill/settings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x60c02950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2020-05-24 21:13:00.394 | WARNING  |   796 | ConfigurationSkill | Failed to update settings, will retry later
2020-05-24 21:16:53.507 | INFO     |   796 | Playback Control Skill | Resolving Player for: some reggae music
2020-05-24 21:16:53.526 | INFO     |   796 | mycroft.util:wait_while_speaking:58 | mycroft.utils.wait_while_speaking() is depreciated, use mycroft.audio.wait_while_speaking() instead.
2020-05-24 21:16:55.087 | INFO     |   796 | mycroft-pandora_mycroftai:_extract_station:426 | generator raised StopIteration
2020-05-24 21:16:55.089 | INFO     |   796 | Mopidy Skill | Checking Mopidy for some reggae music
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
2020-05-24 21:16:57.443 | INFO     |   796 | Mopidy Skill | Mopidy match: ('Reggae', 90, 'generic', '')
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
2020-05-24 21:17:00.396 | INFO     |   796 | Playback Control Skill | Playing with: mycroft-npr-news.mycroftai
2020-05-24 21:17:00.728 | INFO     |   796 | Fairytalez | stop is called
2020-05-24 21:17:00.756 | INFO     |   796 | Mopidy Skill | Handling stop request
2020-05-24 21:17:00.968 | INFO     |   796 | Playback Control Skill | Audio service status: {}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   149    0   149    0     0    711      0 --:--:-- --:--:-- --:--:--   716
100   770    0   770    0     0   2190      0 --:--:-- --:--:-- --:--:--  2190
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     02020-05-24 21:17:05.619 | INFO     |   796 | NewsSkill | Feed: AP
2020-05-24 21:17:05.690 | INFO     |   796 | Playback Control Skill | 
-->Track: AP Hourly Radio News
-->Artist: 
-->Image: file:///opt/mycroft/skills/mycroft-npr-news.mycroftai/images/AP.png
  3 2824k    3 93993    0     0  53440      0  0:00:54  0:00:01  0:00:53 670422020-05-24 21:17:07.491 | INFO     |   796 | Fairytalez | stop is called
2020-05-24 21:17:07.510 | INFO     |   796 | Mopidy Skill | Handling stop request
2020-05-24 21:17:07.743 | INFO     |   796 | Playback Control Skill | Audio service status: {'artist': '', 'album': ''}
2020-05-24 21:17:19.043 | INFO     |   796 | Playback Control Skill | Resolving Player for: something from Bob Marley
2020-05-24 21:17:19.051 | INFO     |   796 | mycroft.util:wait_while_speaking:58 | mycroft.utils.wait_while_speaking() is depreciated, use mycroft.audio.wait_while_speaking() instead.
2020-05-24 21:17:21.850 | INFO     |   796 | Mopidy Skill | Checking Mopidy for something from Bob Marley
2020-05-24 21:17:21.876 | INFO     |   796 | mycroft-pandora_mycroftai:_extract_station:426 | generator raised StopIteration
2020-05-24 21:17:21.881 | ERROR    |   796 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:799 | An error occurred while processing a request in Mopidy Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 92, in extractWithoutOrder
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/skills/common_play_skill.py", line 80, in __handle_play_query
    result = self.CPS_match_query_phrase(search_phrase)
  File "/opt/mycroft/skills/mopidy_skill.forslund/__init__.py", line 113, in CPS_match_query_phrase
    match = self.specific_query(phrase)
  File "/opt/mycroft/skills/mopidy_skill.forslund/__init__.py", line 195, in specific_query
    return self.query_artist(artist)
  File "/opt/mycroft/skills/mopidy_skill.forslund/__init__.py", line 151, in query_artist
    found, conf = (extract_one(artist, self.artists[t].keys()) or
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 230, in extractOne
    return max(best_list, key=lambda i: i[1])
RuntimeError: generator raised StopIteration
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
2020-05-24 21:17:27.421 | INFO     |   796 | Playback Control Skill | Playing with: mycroft-npr-news.mycroftai
2020-05-24 21:17:27.678 | ERROR    |   796 | NewsSkill | Error: 'NoneType' object has no attribute 'strip'
2020-05-24 21:17:27.679 | INFO     |   796 | NewsSkill | Traceback: Traceback (most recent call last):
  File "/opt/mycroft/skills/mycroft-npr-news.mycroftai/__init__.py", line 294, in handle_latest_news
    url = self.get_media_url(rss)
  File "/opt/mycroft/skills/mycroft-npr-news.mycroftai/__init__.py", line 255, in get_media_url
    data = feedparser.parse(station_url.strip())
AttributeError: 'NoneType' object has no attribute 'strip'

2020-05-24 21:17:27.690 | INFO     |   796 | Fairytalez | stop is called
2020-05-24 21:17:27.711 | INFO     |   796 | Mopidy Skill | Handling stop request
2020-05-24 21:17:27.934 | INFO     |   796 | Playback Control Skill | Audio service status: {}
2020-05-24 21:18:49.858 | INFO     |   796 | Playback Control Skill | Resolving Player for: Flobots
2020-05-24 21:18:49.866 | INFO     |   796 | mycroft.util:wait_while_speaking:58 | mycroft.utils.wait_while_speaking() is depreciated, use mycroft.audio.wait_while_speaking() instead.
2020-05-24 21:18:53.052 | INFO     |   796 | Mopidy Skill | Checking Mopidy for Flobots
2020-05-24 21:18:53.087 | INFO     |   796 | mycroft-pandora_mycroftai:_extract_station:426 | generator raised StopIteration
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
2020-05-24 21:18:55.419 | INFO     |   796 | Mopidy Skill | Mopidy match: ('Flobots', 100, 'generic', '')
Removing event mycroft-playback-control.mycroftai:PlayQueryTimeout
2020-05-24 21:18:58.091 | INFO     |   796 | Playback Control Skill | Playing with: mycroft-npr-news.mycroftai
2020-05-24 21:18:58.377 | INFO     |   796 | Fairytalez | stop is called
2020-05-24 21:18:58.399 | INFO     |   796 | Mopidy Skill | Handling stop request
2020-05-24 21:18:58.622 | INFO     |   796 | Playback Control Skill | Audio service status: {}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   452    0   452    0     0   3820      0 --:--:-- --:--:-- --:--:--  3830
100   377  100   377    0     0   1102      0 --:--:-- --:--:-- --:--:--  1102
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     02020-05-24 21:19:02.386 | INFO     |   796 | NewsSkill | Feed: FOX
2020-05-24 21:19:02.443 | INFO     |   796 | Playback Control Skill | 
-->Track: Fox News
-->Artist: 
-->Image: file:///opt/mycroft/skills/mycroft-npr-news.mycroftai/images/FOX.png
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   885  100   885    0     0    922      0 --:--:-- --:--:-- --:--:--   922
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     02020-05-24 21:19:03.592 | INFO     |   796 | Fairytalez | stop is called
2020-05-24 21:19:03.611 | INFO     |   796 | Mopidy Skill | Handling stop request
2020-05-24 21:19:04.038 | INFO     |   796 | Playback Control Skill | Audio service status: {'artist': '', 'album': ''}
```

**Comment by forslund** [comment]
Hi,

I think there are a couple of issues here, the news skill is over-confident on it's match... (There is the same issue with the Spotify skill ("play discover weekly" results in news). Do you have better success with "play some reggae music using mopidy" (possibly typed in the cli as "mopidy" may be tricky for the STT)

The stack trace looks like a real issue with the skill, I'll look into that.
